### ISSUE TITLE
Ambiguous infshop unlock conditions

### ISSUE THREAD

**Issue by Bleb1k** [rando-idiot/Terminus.JS#10]
Somehow I have unlocked `infshop()` access

**Comment by rando-idiot** [comment]
made it autounlock for debug reasons, forgot to remove that

**Comment by rando-idiot** [comment]
NEVERMIND THE EVIL JAVASCRIPT MAGIC IS EATING MY BRAIN OUT

**Comment by rando-idiot** [comment]
fixed
