### ISSUE TITLE
Details in code

### ISSUE THREAD

**Issue by Bleb1k** [rando-idiot/Terminus.JS#13]
- [x] Variable naming is inconsistent, bad naming convention
- [x] Using var everywhere, no matter the cause #11 
- [x] Code readability and ease of understanding/following the execution #12 

I suggest watching a few videos, namely:
- [Naming Things in Code](https://www.youtube.com/watch?v=-J3wNP6u5YU)
- [Don't Write Comments](https://www.youtube.com/watch?v=Bf7vDBBOBUA)
- [The 3 Laws of Writing Readable Code](https://www.youtube.com/watch?v=-AzSRHiV9Cc)

**Comment by rando-idiot** [comment]
god damn it i probably have to do this

**Comment by rando-idiot** [comment]
aight i did the things
