### ISSUE TITLE
reminder to fix this:

### ISSUE THREAD

**Issue by rando-idiot** [rando-idiot/Terminus.JS#15]
> heres how i read this:
> 
> if debtflag is set, follow these instructions:
> 
> if points are less then zero, set points to zero and immediately reset debtflag
> 
> or if points are above zero, and debtflag is set, reset debtflag and announce getting out of debt
> 
> 
> 
> so, if you have debt, and your points are non-zero, reset debt, else if points are zero, reset debtflag and announce getting out of debt! what 😅 

 _Originally posted by @Bleb1k in [4c6eacc](https://github.com/rando-idiot/Terminus.JS/commit/4c6eaccdefa47027df1dda6944af72e1b46c48a6#r147363672)_

**Comment by Bleb1k** [comment]
Should be fixed now that you've merged my PR

**Comment by rando-idiot** [comment]
aight
also
![image](https://github.com/user-attachments/assets/e6df0314-3352-4853-b75f-56d04671e12d)

**Comment by rando-idiot** [comment]
nvm fixed it by changing to semicolon

**Comment by Bleb1k** [comment]
That's an interesting way to present an Issue.

**Comment by rando-idiot** [comment]
it is, isnt it?

**Comment by Bleb1k** [comment]
unpin this issue
