### ISSUE TITLE
Text return was a bad idea

### ISSUE THREAD

**Issue by Bleb1k** [rando-idiot/Terminus.JS#20]
## Issue
If we return text as a string instead of using console.log, it literally prints this text, without formating `\n` or any other escape character

## How to replicate
Run under Microsoft Edge browser

## How to fix
Use console.log instead of returns

**Comment by rando-idiot** [comment]
Are you telling me
greg

**Comment by rando-idiot** [comment]
also ok i do that

**Comment by rando-idiot** [comment]
HOWEVER. It was you who made the bug. It is, in fact, your job to fix it. Does this seem fair enough? Cool.

**Comment by Bleb1k** [comment]
it's my but yeah

**Comment by rando-idiot** [comment]
make a pull request with the fixed bug

**Comment by Bleb1k** [comment]
Open this issue, I'll make a PR into this, just assign me to do it

**Comment by rando-idiot** [comment]
k

**Comment by Bleb1k** [comment]
Resolved with #21

**Comment by rando-idiot** [comment]
coooooooooooolioooooooooooo
