### ISSUE TITLE
Skills disaster

### ISSUE THREAD

**Issue by Bleb1k** [rando-idiot/Terminus.JS#28]
It is written in a hard to extend way.
I suggest rewriting it as a [class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes).

For more references see [Achievement](https://github.com/Bleb1k/Terminus.JS/blob/2d5505b9c93f22da5dc6652d1a33b7b9850db537/src/logi/achievements.js) and [Terminal](https://github.com/Bleb1k/Terminus.JS/blob/2d5505b9c93f22da5dc6652d1a33b7b9850db537/src/terminal.js) implementations.

**Comment by rando-idiot** [comment]
i was aware that the skills shit was terrible i mostly just wanted to get it out quickly because i had other shit going on

**Comment by rando-idiot** [comment]
it was entirely meant to be temporary
