### ISSUE TITLE
cannot use functions with parameters in console emulator

### ISSUE THREAD

**Issue by rando-idiot** [rando-idiot/Terminus.JS#30]
![image](https://github.com/user-attachments/assets/d04d6c3b-f0ea-4a44-9e85-6f97fd2f2e4d)

**Comment by rando-idiot** [comment]
![image](https://github.com/user-attachments/assets/954740b0-b81f-4c8d-9700-cacaab0f1fa2)
more examples

**Comment by rando-idiot** [comment]
@Bleb1k please fix this it literally breaks half of the commands in the game

**Comment by Bleb1k** [comment]
Oops, forgot about this

**Comment by rando-idiot** [comment]
real

**Comment by rando-idiot** [comment]
fixed in #37
