### ISSUE TITLE
Price in infshop does not match actual price paid

### ISSUE THREAD

**Issue by BDLCoding** [rando-idiot/Terminus.JS#33]
Looks like players are paying based off
`        game.points -= 5 +
            game.upgpriceboost * game.upgpriceboost * game.difficulty;`
          
but shop displayed cost is 
`stepone: $${
                    5 + game.upgpriceboost * game.difficulty`

so actual cost is multipled by an extra upgpriceboost when subtracted from players points. 

Affects all items in infshop.

**Comment by rando-idiot** [comment]
cool sorry for not noticing this, will be fixed in next patch

**Comment by rando-idiot** [comment]
it has been fixed, you'll see when i actually push the next patch
