### ISSUE TITLE
First message

### ISSUE THREAD

**Issue by Bleb1k** [rando-idiot/Terminus.JS#4]
`use info(); for, well, info. lol.`
this is not readable

you may as well display this at the start
also, there is a convention to have this style of thing named `help`
and have a structure for it like so:
```
$ deno help
Deno: A modern JavaScript and TypeScript runtime

Usage: deno [OPTIONS] [COMMAND]

Commands:
  Execution:
    run          Run a JavaScript or TypeScript program, or a task
                  deno run main.ts  |  deno run --allow-net=google.com main.ts  |  deno main.ts
    serve        Run a server
                  deno serve main.ts
    task         Run a task defined in the configuration file
                  deno task dev
    repl         Start an interactive Read-Eval-Print Loop (REPL) for Deno
    eval         Evaluate a script from the command line

  Dependency management:
    add          Add dependencies
                  deno add @std/assert  |  deno add npm:express
    install      Install script as an executable
    uninstall    Uninstall a script previously installed with deno install
    remove       Remove dependencies from the configuration file
```

for your application it may look like
```
$ help()
Terminus.JS

Commands:
  help()    Show this.
  shop()    Show a shop.
  update()  Update your money. (what does this mean???)
  etc...
```

**Comment by rando-idiot** [comment]
Cool, ill add this asap!

**Comment by rando-idiot** [comment]
(update btw is how you get more points in case you couldnt tell)

**Comment by rando-idiot** [comment]
(ill make that tutorial bit better later on)

**Comment by rando-idiot** [comment]
uhhhh le suggested code no workies (i feel like im being dumb ;-;)

**Comment by rando-idiot** [comment]
i say that because upon checking it in a syntax validator it said "no"

**Comment by Bleb1k** [comment]
i need to know what is your workspace

**Comment by Bleb1k** [comment]
and why you have to use external syntax validator

**Comment by rando-idiot** [comment]
im using visual studio and it says everything is good syntax no matter what so :3

**Comment by Bleb1k** [comment]
there's difference between [visual studio](https://visualstudio.microsoft.com/) and [VSCode](https://code.visualstudio.com/), plus setup is not only the app, but tools (extensions) in the app, and configs

**Comment by rando-idiot** [comment]
this thingy

**Comment by Bleb1k** [comment]
use this for web: [VSCode](https://code.visualstudio.com/)

**Comment by Bleb1k** [comment]
it have the features i mentioned earlier

**Comment by rando-idiot** [comment]
alr yippee

**Comment by rando-idiot** [comment]
holy shit this is way better

**Comment by rando-idiot** [comment]
oh yeah i did this i forgor
