### ISSUE TITLE
No saves

### ISSUE THREAD

**Issue by Bleb1k** [rando-idiot/Terminus.JS#5]
Everything resets after a page reload

I suggest using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) as it is easier to integrate with small games

Later on it is possible to use [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) to be able to manipulate data more efficiently
(This assumes you have to handle 1-2 gigabytes of data at a time)

**Comment by rando-idiot** [comment]
In actuality i was going to inplement an entirely different save system. Consider the following: yk how in older games when they gave you the express option to save they also gave you a code to go along with it? i was thinking of implementing that

**Comment by Bleb1k** [comment]
> older games when they gave you the express option to save they also gave you a code to go along with it? i was thinking of implementing that

This is a good way of adding a backup system, but can you imagine having to open a separate backup file each time you want to save/load? I think this is a bother

**Comment by rando-idiot** [comment]
its not a file, its just a shrimple little string of text, at most 6 chars long

**Comment by Bleb1k** [comment]
i mean, you have to store it somewhere, right? =)

**Comment by rando-idiot** [comment]
your brain or your name

**Comment by rando-idiot** [comment]
ngl excited to be able to close this someday

**Comment by rando-idiot** [comment]
forgot i already fixed this
